<?php
// patient_details_print.php - Print Patient Details
// Start output buffering at the VERY beginning
if (ob_get_level()) ob_end_clean();
ob_start();

error_reporting(E_ALL);
ini_set('display_errors', 1);
// Now include files after basic validation
require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/inc_all.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/plugins/TCPDF/tcpdf.php';

// Get patient ID
$patient_id = isset($_GET['patient_id']) ? intval($_GET['patient_id']) : 0;

if ($patient_id == 0) {
    // Clean buffer and show error
    ob_clean();
    die('Invalid patient ID');
}

// Get facility information (using primary/active facility)
$facility_sql = "SELECT * FROM facilities WHERE is_active = 1 LIMIT 1";
$facility_result = $mysqli->query($facility_sql);
$facility = $facility_result->fetch_assoc();

// Get patient data
$patient_sql = "SELECT p.*, 
                       u_created.user_name as created_by_name,
                       u_updated.user_name as updated_by_name
                FROM patients p 
                LEFT JOIN users u_created ON p.created_by = u_created.user_id
                LEFT JOIN users u_updated ON p.updated_by = u_updated.user_id
                WHERE p.patient_id = ? AND p.patient_status != 'ARCHIVED'";
$patient_stmt = $mysqli->prepare($patient_sql);
$patient_stmt->bind_param("i", $patient_id);
$patient_stmt->execute();
$patient_result = $patient_stmt->get_result();
$patient = $patient_result->fetch_assoc();

if (!$patient) {
    ob_clean();
    die('Patient not found');
}

// Get next of kin
$kin_sql = "SELECT * FROM patient_next_of_kin WHERE patient_id = ?";
$kin_stmt = $mysqli->prepare($kin_sql);
$kin_stmt->bind_param("i", $patient_id);
$kin_stmt->execute();
$kin_result = $kin_stmt->get_result();
$next_of_kin = $kin_result->fetch_assoc();

// Get patient visit history
$visits_sql = "SELECT v.*, 
                       d.department_name, 
                       u.user_name as provider_name,
                       f.facility_name
               FROM visits v 
               LEFT JOIN departments d ON v.department_id = d.department_id
               LEFT JOIN users u ON v.attending_provider_id = u.user_id
               LEFT JOIN facilities f ON v.facility_code = f.facility_internal_code
               WHERE v.patient_id = ?
               ORDER BY v.visit_datetime DESC
               LIMIT 10";
$visits_stmt = $mysqli->prepare($visits_sql);
$visits_stmt->bind_param("i", $patient_id);
$visits_stmt->execute();
$visits_result = $visits_stmt->get_result();

// Clean any output that might have been generated by included files
ob_clean();

// Create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor($facility['facility_name'] ?? 'Medical Facility');
$pdf->SetTitle('Patient Details - ' . $patient['first_name'] . ' ' . $patient['last_name']);
$pdf->SetSubject('Patient Medical Record');

// Remove default header/footer
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);

// Set margins
$pdf->SetMargins(15, 15, 15);
$pdf->SetAutoPageBreak(TRUE, 15);

// Add a page
$pdf->AddPage();

// Set font
$pdf->SetFont('helvetica', '', 10);

// Facility Header with Logo
$header = '
<table border="0" cellpadding="5" cellspacing="0" width="100%">
    <tr>
        <td width="30%">';

// Add facility logo if exists (you can add logo functionality later)
$header .= '</td>
        <td width="70%" style="text-align: center;">
            <h1 style="color: #2c3e50; margin: 0; font-size: 24px;">' . htmlspecialchars($facility['facility_name'] ?? 'Medical Facility') . '</h1>
            <p style="color: #7f8c8d; margin: 5px 0; font-size: 12px;">' . htmlspecialchars($facility['physical_address'] ?? 'Address not specified') . '</p>
            <p style="color: #7f8c8d; margin: 5px 0; font-size: 12px;">Phone: ' . htmlspecialchars($facility['phone'] ?? 'N/A') . ' | Email: ' . htmlspecialchars($facility['email'] ?? 'N/A') . '</p>
            <p style="color: #7f8c8d; margin: 5px 0; font-size: 12px;">MFL Code: ' . htmlspecialchars($facility['mfl_code'] ?? 'N/A') . ' | Facility Code: ' . htmlspecialchars($facility['facility_internal_code'] ?? 'N/A') . '</p>
        </td>
    </tr>
</table>
<hr style="border: 1px solid #34495e; margin: 10px 0;">';

$pdf->writeHTML($header, true, false, true, false, '');

// Patient Details Section
$full_name = $patient['first_name'] . 
            ($patient['middle_name'] ? ' ' . $patient['middle_name'] : '') . 
            ' ' . $patient['last_name'];

// Calculate age
$age = '';
if (!empty($patient['date_of_birth'])) {
    $birthDate = new DateTime($patient['date_of_birth']);
    $today = new DateTime();
    $age = $today->diff($birthDate)->y . ' years';
}

// Format sex display
$sex_display = '';
switch($patient['sex'] ?? '') {
    case 'M': $sex_display = 'Male'; break;
    case 'F': $sex_display = 'Female'; break;
    case 'I': $sex_display = 'Intersex'; break;
    default: $sex_display = 'N/A';
}

// Format ID type display
$id_type_display = '';
switch($patient['id_type'] ?? '') {
    case 'NATIONAL_ID': $id_type_display = 'National ID'; break;
    case 'BIRTH_CERT': $id_type_display = 'Birth Certificate'; break;
    case 'PASSPORT': $id_type_display = 'Passport'; break;
    case 'ALIEN_ID': $id_type_display = 'Alien ID'; break;
    default: $id_type_display = 'N/A';
}

$patient_details = '
<h2 style="color: #37a333; background-color: #ecf0f1; padding: 8px; font-size: 16px;">PATIENT DETAILS</h2>
<table border="0" cellpadding="5" cellspacing="0" width="100%" style="font-size: 10px;">
    <tr>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;"><strong>Full Name:</strong></td>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;">' . htmlspecialchars($full_name) . '</td>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;"><strong>Medical Record No:</strong></td>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;">' . htmlspecialchars($patient['patient_mrn']) . '</td>
    </tr>
    <tr>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;"><strong>Date of Birth:</strong></td>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;">' . (!empty($patient['date_of_birth']) ? date('M j, Y', strtotime($patient['date_of_birth'])) : 'N/A') . '</td>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;"><strong>Age:</strong></td>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;">' . htmlspecialchars($age) . '</td>
    </tr>
    <tr>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;"><strong>Sex:</strong></td>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;">' . htmlspecialchars($sex_display) . '</td>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;"><strong>Blood Group:</strong></td>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;">' . htmlspecialchars($patient['blood_group'] ?? 'N/A') . '</td>
    </tr>
    <tr>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;"><strong>ID Type:</strong></td>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;">' . htmlspecialchars($id_type_display) . '</td>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;"><strong>ID Number:</strong></td>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;">' . htmlspecialchars($patient['id_number'] ?? 'N/A') . '</td>
    </tr>
    <tr>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;"><strong>Primary Phone:</strong></td>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;">' . htmlspecialchars($patient['phone_primary']) . '</td>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;"><strong>Secondary Phone:</strong></td>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;">' . htmlspecialchars($patient['phone_secondary'] ?? 'N/A') . '</td>
    </tr>
    <tr>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;"><strong>Email:</strong></td>
        <td width="75%" style="border-bottom: 1px solid #bdc3c7;" colspan="3">' . htmlspecialchars($patient['email'] ?? 'N/A') . '</td>
    </tr>
    <tr>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;"><strong>Registered On:</strong></td>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;">' . date('M j, Y g:i A', strtotime($patient['created_at'])) . '</td>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;"><strong>Status:</strong></td>
        <td width="25%" style="border-bottom: 1px solid #bdc3c7;">' . htmlspecialchars($patient['patient_status']) . '</td>
    </tr>
</table>
<br>';

$pdf->writeHTML($patient_details, true, false, true, false, '');

// Patient Address Section
$address_parts = [];
if (!empty($patient['village'])) $address_parts[] = $patient['village'];
if (!empty($patient['ward'])) $address_parts[] = $patient['ward'];
if (!empty($patient['sub_county'])) $address_parts[] = $patient['sub_county'];
if (!empty($patient['county'])) $address_parts[] = $patient['county'];

$full_address = implode(', ', $address_parts);
if (empty($full_address)) $full_address = 'Not specified';

$address_details = '
<h2 style="color: #2c3e50; background-color: #ecf0f1; padding: 8px; font-size: 16px;">ADDRESS INFORMATION</h2>
<table border="0" cellpadding="5" cellspacing="0" width="100%" style="font-size: 10px;">
    <tr>
        <td width="30%" style="border-bottom: 1px solid #bdc3c7;"><strong>County:</strong></td>
        <td width="70%" style="border-bottom: 1px solid #bdc3c7;">' . htmlspecialchars($patient['county'] ?? 'N/A') . '</td>
    </tr>
    <tr>
        <td width="30%" style="border-bottom: 1px solid #bdc3c7;"><strong>Sub-County:</strong></td>
        <td width="70%" style="border-bottom: 1px solid #bdc3c7;">' . htmlspecialchars($patient['sub_county'] ?? 'N/A') . '</td>
    </tr>
    <tr>
        <td width="30%" style="border-bottom: 1px solid #bdc3c7;"><strong>Ward:</strong></td>
        <td width="70%" style="border-bottom: 1px solid #bdc3c7;">' . htmlspecialchars($patient['ward'] ?? 'N/A') . '</td>
    </tr>
    <tr>
        <td width="30%" style="border-bottom: 1px solid #bdc3c7;"><strong>Village/Area:</strong></td>
        <td width="70%" style="border-bottom: 1px solid #bdc3c7;">' . htmlspecialchars($patient['village'] ?? 'N/A') . '</td>
    </tr>
    <tr>
        <td width="30%" style="border-bottom: 1px solid #bdc3c7;"><strong>Postal Address:</strong></td>
        <td width="70%" style="border-bottom: 1px solid #bdc3c7;">' . htmlspecialchars($patient['postal_address'] ?? 'N/A') . '</td>
    </tr>
    <tr>
        <td width="30%" style="border-bottom: 1px solid #bdc3c7;"><strong>Postal Code:</strong></td>
        <td width="70%" style="border-bottom: 1px solid #bdc3c7;">' . htmlspecialchars($patient['postal_code'] ?? 'N/A') . '</td>
    </tr>
    <tr>
        <td width="30%"><strong>Full Address:</strong></td>
        <td width="70%">' . htmlspecialchars($full_address) . '</td>
    </tr>
</table>
<br>';

$pdf->writeHTML($address_details, true, false, true, false, '');

// Next of Kin Section
$next_of_kin_html = '
<h2 style="color: #2c3e50; background-color: #ecf0f1; padding: 8px; font-size: 16px;">NEXT OF KIN</h2>';

if ($next_of_kin) {
    $next_of_kin_html .= '
    <table border="0" cellpadding="5" cellspacing="0" width="100%" style="font-size: 10px;">
        <tr>
            <td width="30%" style="border-bottom: 1px solid #bdc3c7;"><strong>Full Name:</strong></td>
            <td width="70%" style="border-bottom: 1px solid #bdc3c7;">' . htmlspecialchars($next_of_kin['full_name']) . '</td>
        </tr>
        <tr>
            <td width="30%" style="border-bottom: 1px solid #bdc3c7;"><strong>Relationship:</strong></td>
            <td width="70%" style="border-bottom: 1px solid #bdc3c7;">' . htmlspecialchars($next_of_kin['relationship'] ?? 'N/A') . '</td>
        </tr>
        <tr>
            <td width="30%"><strong>Phone Number:</strong></td>
            <td width="70%">' . htmlspecialchars($next_of_kin['phone'] ?? 'N/A') . '</td>
        </tr>
    </table>';
} else {
    $next_of_kin_html .= '
    <p style="text-align: center; color: #7f8c8d; font-style: italic;">No next of kin information available</p>';
}

$next_of_kin_html .= '<br>';

$pdf->writeHTML($next_of_kin_html, true, false, true, false, '');

// Visit History Section (if any visits exist)
if ($visits_result->num_rows > 0) {
    $visit_history = '
    <h2 style="color: #2c3e50; background-color: #ecf0f1; padding: 8px; font-size: 16px;">RECENT VISIT HISTORY (Last 10 visits)</h2>
    <table border="1" cellpadding="5" cellspacing="0" width="100%" style="font-size: 9px; border-collapse: collapse;">
        <thead>
            <tr style="background-color: #34495e; color: white;">
                <th width="20%">Visit Date & Time</th>
                <th width="15%">Visit Type</th>
                <th width="25%">Department</th>
                <th width="20%">Provider</th>
                <th width="20%">Status</th>
            </tr>
        </thead>
        <tbody>';
    
    while ($visit = $visits_result->fetch_assoc()) {
        $status_color = '';
        switch($visit['visit_status']) {
            case 'ACTIVE': $status_color = '#28a745'; break;
            case 'CLOSED': $status_color = '#007bff'; break;
            default: $status_color = '#6c757d';
        }
        
        $visit_type_display = '';
        switch($visit['visit_type']) {
            case 'OPD': $visit_type_display = 'OPD'; break;
            case 'IPD': $visit_type_display = 'IPD'; break;
            case 'EMERGENCY': $visit_type_display = 'Emergency'; break;
            default: $visit_type_display = htmlspecialchars($visit['visit_type']);
        }
        
        $visit_history .= '
            <tr>
                <td>' . date('M j, Y H:i', strtotime($visit['visit_datetime'])) . '</td>
                <td>' . htmlspecialchars($visit_type_display) . '</td>
                <td>' . htmlspecialchars($visit['department_name'] ?? 'N/A') . '</td>
                <td>' . htmlspecialchars($visit['provider_name'] ?? 'N/A') . '</td>
                <td style="color: ' . $status_color . ';">' . htmlspecialchars($visit['visit_status']) . '</td>
            </tr>';
    }
    
    $visit_history .= '
        </tbody>
    </table>';
    
    $pdf->writeHTML($visit_history, true, false, true, false, '');
}

// Footer with generation info
$pdf->SetY(-30);
$footer = '
<hr style="border: 0.5px solid #bdc3c7; margin: 10px 0;">
<table border="0" cellpadding="5" cellspacing="0" width="100%" style="font-size: 8px; color: #7f8c8d;">
    <tr>
        <td width="50%">Generated on: ' . date('M j, Y g:i A') . '</td>
        <td width="50%" style="text-align: right;">Page ' . $pdf->getAliasNumPage() . ' of ' . $pdf->getAliasNbPages() . '</td>
    </tr>
    <tr>
        <td width="50%">Generated by: ' . htmlspecialchars($_SESSION['user_name'] ?? 'System') . '</td>
        <td width="50%" style="text-align: right;">Facility: ' . htmlspecialchars($facility['facility_name'] ?? 'Medical Facility') . '</td>
    </tr>
    <tr>
        <td width="100%" colspan="2" style="text-align: center;">This is an official document from ' . htmlspecialchars($facility['facility_name'] ?? 'Medical Facility') . '</td>
    </tr>
</table>';

$pdf->writeHTML($footer, true, false, true, false, '');

// Close and output PDF document
$pdf->Output('patient_details_' . $patient['patient_mrn'] . '.pdf', 'I');
exit;