<?php
// Start output buffering at the VERY beginning
if (ob_get_level()) ob_end_clean();
ob_start();

error_reporting(E_ALL);
ini_set('display_errors', 1);
// Now include files after basic validation
require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/inc_all.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/plugins/TCPDF/tcpdf.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/load_company_settings.php';

// Get patient ID first
$patient_id = isset($_GET['patient_id']) ? intval($_GET['patient_id']) : 0;

if ($patient_id == 0) {
    // Clean buffer and show error
    ob_clean();
    die('Invalid patient ID');
}

// Get patient data with emergency contact
$patient_sql = "SELECT p.*, 
                       ec.contact_name, ec.contact_relationship, ec.contact_phone, 
                       ec.contact_mobile, ec.contact_email,
                       u_created.user_name as created_by_name,
                       u_updated.user_name as updated_by_name
                FROM patients p 
                LEFT JOIN patient_emergency_contacts ec ON p.patient_id = ec.patient_id
                LEFT JOIN users u_created ON p.created_by = u_created.user_id
                LEFT JOIN users u_updated ON p.updated_by = u_updated.user_id
                WHERE p.patient_id = ? AND p.patient_archived_at IS NULL";
$patient_stmt = $mysqli->prepare($patient_sql);
$patient_stmt->bind_param("i", $patient_id);
$patient_stmt->execute();
$patient_result = $patient_stmt->get_result();
$patient = $patient_result->fetch_assoc();

if (!$patient) {
    $_SESSION['alert_type'] = "error";
    $_SESSION['alert_message'] = "Patient not found";
    header("Location: patients.php");
    exit;
}

// Clean any output that might have been generated by included files
ob_clean();

// Create new PDF document
$pdf = new TCPDF('L', 'mm', array(86, 54), true, 'UTF-8', false); // Credit card size

// Set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor($session_company_name);
$pdf->SetTitle('Patient & Guardian Cards - ' . $patient['patient_first_name'] . ' ' . $patient['patient_last_name']);
$pdf->SetSubject('Medical ID Cards');

// Remove default header/footer
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);

// Set margins
$pdf->SetMargins(3, 3, 3);
$pdf->SetAutoPageBreak(FALSE);

// Calculate age
$age = '';
if (!empty($patient['patient_dob'])) {
    $birthDate = new DateTime($patient['patient_dob']);
    $today = new DateTime();
    $age = $today->diff($birthDate)->y;
}

$full_name = $patient['patient_first_name'] . 
            ($patient['patient_middle_name'] ? ' ' . $patient['patient_middle_name'] : '') . 
            ' ' . $patient['patient_last_name'];

// Function to truncate text
function truncateText($text, $length) {
    if (strlen($text) > $length) {
        return substr($text, 0, $length - 3) . '...';
    }
    return $text;
}

// PATIENT CARD
$pdf->AddPage();

// Card border and background
$pdf->SetFillColor(255, 255, 255);
$pdf->Rect(0, 0, 86, 54, 'F');
$pdf->SetLineStyle(array('width' => 0.3, 'color' => array(200, 200, 200)));
$pdf->Rect(1, 1, 84, 52);

// Header with medical symbol and title
$pdf->SetFillColor(55, 163, 51); // Medical green
$pdf->Rect(1, 1, 84, 6, 'F');
$pdf->SetTextColor(255, 255, 255);
$pdf->SetFont('helvetica', 'B', 9);
$pdf->SetXY(1, 1.5);
$pdf->Cell(84, 4, 'PATIENT ID CARD', 0, 1, 'C');

// Medical symbol (cross)
$pdf->SetTextColor(255, 255, 255);
$pdf->SetFont('zapfdingbats', '', 7);
$pdf->SetXY(4, 1.5);
$pdf->Cell(3, 4, chr(65), 0, 0, 'L'); // Medical cross symbol

// Patient photo area (smaller to save space)
$pdf->SetFillColor(245, 245, 245);
$pdf->Rect(67, 8, 16, 20, 'F');
$pdf->SetTextColor(180, 180, 180);
$pdf->SetFont('helvetica', '', 5);
$pdf->SetXY(67, 16);
$pdf->Cell(16, 3, 'PHOTO', 0, 1, 'C');

// Patient information - Compact layout
$pdf->SetTextColor(0, 0, 0);

// Row 1: Name and MRN
$pdf->SetFont('helvetica', 'B', 7);
$pdf->SetXY(3, 8);
$pdf->Cell(12, 3, 'NAME:', 0, 0, 'L');
$pdf->SetFont('helvetica', '', 7);
$pdf->SetXY(15, 8);
$pdf->Cell(50, 3, truncateText($full_name, 30), 0, 1, 'L');

$pdf->SetFont('helvetica', 'B', 7);
$pdf->SetXY(3, 11.5);
$pdf->Cell(12, 3, 'MRN:', 0, 0, 'L');
$pdf->SetFont('helvetica', '', 7);
$pdf->SetXY(15, 11.5);
$pdf->Cell(25, 3, $patient['patient_mrn'], 0, 1, 'L');

// Row 2: DOB and Age
$pdf->SetFont('helvetica', 'B', 7);
$pdf->SetXY(3, 15);
$pdf->Cell(12, 3, 'DOB:', 0, 0, 'L');
$pdf->SetFont('helvetica', '', 7);
$pdf->SetXY(15, 15);
$pdf->Cell(25, 3, !empty($patient['patient_dob']) ? date('m/d/Y', strtotime($patient['patient_dob'])) : 'N/A', 0, 1, 'L');

$pdf->SetFont('helvetica', 'B', 7);
$pdf->SetXY(40, 15);
$pdf->Cell(8, 3, 'AGE:', 0, 0, 'L');
$pdf->SetFont('helvetica', '', 7);
$pdf->SetXY(48, 15);
$pdf->Cell(10, 3, $age ? $age . 'y' : 'N/A', 0, 1, 'L');

// Row 3: Gender and Blood Type
$pdf->SetFont('helvetica', 'B', 7);
$pdf->SetXY(3, 18.5);
$pdf->Cell(12, 3, 'GENDER:', 0, 0, 'L');
$pdf->SetFont('helvetica', '', 7);
$pdf->SetXY(15, 18.5);
$pdf->Cell(15, 3, $patient['patient_gender'] ? substr($patient['patient_gender'], 0, 1) : 'N/A', 0, 1, 'L');

$pdf->SetFont('helvetica', 'B', 7);
$pdf->SetXY(30, 18.5);
$pdf->Cell(15, 3, 'ID NO:', 0, 0, 'L');
$pdf->SetFont('helvetica', '', 7);
$pdf->SetXY(42, 18.5);
$pdf->Cell(10, 3, $patient['patient_id_number'] ?: 'N/A', 0, 1, 'L');

// Row 4: Contact info
$pdf->SetFont('helvetica', 'B', 7);
$pdf->SetXY(3, 22);
$pdf->Cell(15, 3, 'PHONE:', 0, 0, 'L');
$pdf->SetFont('helvetica', '', 7);
$pdf->SetXY(18, 22);
$pdf->Cell(45, 3, $patient['patient_mobile'] ?: $patient['patient_phone'] ?: 'N/A', 0, 1, 'L');

// Emergency contact section - more compact
$pdf->SetFillColor(255, 245, 245);
$pdf->Rect(1, 25, 84, 6, 'F');
$pdf->SetTextColor(200, 0, 0);
$pdf->SetFont('helvetica', 'B', 5);
$pdf->SetXY(3, 26);
$pdf->Cell(20, 3, 'EMERGENCY CONTACT:', 0, 0, 'L');
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('helvetica', '', 6);
$pdf->SetXY(23, 26);
$pdf->Cell(40, 3, truncateText($patient['contact_name'] ?: 'N/A', 30), 0, 1, 'L');

$pdf->SetFont('helvetica', 'B', 6);
$pdf->SetXY(3, 29);
$pdf->Cell(15, 3, 'CONTACT PH:', 0, 0, 'L');
$pdf->SetFont('helvetica', '', 6);
$pdf->SetXY(18, 29);
$pdf->Cell(45, 3, $patient['contact_mobile'] ?: $patient['contact_phone'] ?: 'N/A', 0, 1, 'L');

// Allergies/Medical notes
$pdf->SetFillColor(240, 240, 255);
$pdf->Rect(1, 32, 84, 5, 'F');
$pdf->SetTextColor(0, 0, 128);
$pdf->SetFont('helvetica', 'B', 6);
$pdf->SetXY(3, 33);
$pdf->Cell(12, 3, 'ALLERGIES:', 0, 0, 'L');
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('helvetica', '', 6);
$pdf->SetXY(15, 33);
//$pdf->Cell(65, 3, truncateText($patient['patient_allergies'] ?: 'None reported', 50), 0, 1, 'L');

// Footer with facility info
$pdf->SetFillColor(55, 163, 51);
$pdf->Rect(1, 37, 84, 4, 'F');
$pdf->SetTextColor(255, 255, 255);
$pdf->SetFont('helvetica', 'B', 6);
$pdf->SetXY(1, 37.5);
$pdf->Cell(84, 3, $session_company_name, 0, 1, 'C');

$pdf->SetTextColor(100, 100, 100);
$pdf->SetFont('helvetica', 'I', 5);
$pdf->SetXY(1, 41.5);
$pdf->Cell(84, 2, 'Issued: ' . date('m/d/Y'), 0, 1, 'C');
$pdf->SetXY(1, 44);
//$pdf->Cell(84, 2, 'Facility Ph: ' . ($session_company_phone ?: 'N/A'), 0, 1, 'C');

// Barcode area (optional)
$pdf->SetFillColor(245, 245, 245);
$pdf->Rect(60, 41, 22, 10, 'F');
$pdf->SetTextColor(150, 150, 150);
$pdf->SetFont('helvetica', '', 4);
$pdf->SetXY(60, 46);
$pdf->Cell(22, 2, 'SCAN FOR RECORDS', 0, 1, 'C');

// PATIENT GUARDIAN CARD
$pdf->AddPage();

// Card border and background
$pdf->SetFillColor(255, 255, 255);
$pdf->Rect(0, 0, 86, 54, 'F');
$pdf->SetLineStyle(array('width' => 0.3, 'color' => array(200, 200, 200)));
$pdf->Rect(1, 1, 84, 52);

// Header with guardian symbol and title
$pdf->SetFillColor(41, 128, 185); // Blue color for guardian
$pdf->Rect(1, 1, 84, 6, 'F');
$pdf->SetTextColor(255, 255, 255);
$pdf->SetFont('helvetica', 'B', 9);
$pdf->SetXY(1, 1.5);
$pdf->Cell(84, 4, 'PATIENT GUARDIAN CARD', 0, 1, 'C');

// Guardian symbol
$pdf->SetTextColor(255, 255, 255);
$pdf->SetFont('zapfdingbats', '', 7);
$pdf->SetXY(4, 1.5);
$pdf->Cell(3, 4, chr(67), 0, 0, 'L'); // Person symbol

// Guardian photo area
$pdf->SetFillColor(245, 245, 245);
$pdf->Rect(67, 8, 16, 20, 'F');
$pdf->SetTextColor(180, 180, 180);
$pdf->SetFont('helvetica', '', 5);
$pdf->SetXY(67, 16);
$pdf->Cell(16, 3, 'GUARDIAN PHOTO', 0, 1, 'C');

// Guardian information - Compact layout
$pdf->SetTextColor(0, 0, 0);

// Row 1: Guardian Name
$pdf->SetFont('helvetica', 'B', 7);
$pdf->SetXY(3, 8);
$pdf->Cell(18, 3, 'GUARDIAN:', 0, 0, 'L');
$pdf->SetFont('helvetica', '', 7);
$pdf->SetXY(18, 8);
$pdf->Cell(47, 3, truncateText($patient['contact_name'] ?: 'Not Specified', 30), 0, 1, 'L');

// Row 2: Relationship and Contact
$pdf->SetFont('helvetica', 'B', 3);
$pdf->SetXY(3, 11.5);
$pdf->Cell(20, 3, 'RELATIONSHIP:', 0, 0, 'L');
$pdf->SetFont('helvetica', '', 7);
$pdf->SetXY(20, 11.5);
$pdf->Cell(25, 3, truncateText($patient['contact_relationship'] ?: 'N/A', 20), 0, 1, 'L');

$pdf->SetFont('helvetica', 'B', 7);
$pdf->SetXY(45, 11.5);
$pdf->Cell(10, 3, 'PHONE:', 0, 0, 'L');
$pdf->SetFont('helvetica', '', 5);
$pdf->SetXY(53, 11.5);
$pdf->Cell(30, 3, $patient['contact_mobile'] ?: $patient['contact_phone'] ?: 'N/A', 0, 1, 'L');

// Row 3: Email
$pdf->SetFont('helvetica', 'B', 7);
$pdf->SetXY(3, 15);
$pdf->Cell(12, 3, 'EMAIL:', 0, 0, 'L');
$pdf->SetFont('helvetica', '', 6);
$pdf->SetXY(13, 15);
$pdf->Cell(50, 3, truncateText($patient['contact_email'] ?: 'N/A', 40), 0, 1, 'L');

// Patient information section
$pdf->SetFillColor(240, 245, 255);
$pdf->Rect(1, 18, 84, 10, 'F');
$pdf->SetTextColor(41, 128, 185);
$pdf->SetFont('helvetica', 'B', 5);
$pdf->SetXY(3, 19);
$pdf->Cell(25, 3, 'PATIENT UNDER CARE:', 0, 0, 'L');
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('helvetica', '', 7);
$pdf->SetXY(28, 19);
$pdf->Cell(50, 3, truncateText($full_name, 30), 0, 1, 'L');

// Patient details in compact grid
$pdf->SetFont('helvetica', 'B', 6);
$pdf->SetXY(3, 22.5);
$pdf->Cell(15, 3, 'MRN:', 0, 0, 'L');
$pdf->SetFont('helvetica', '', 6);
$pdf->SetXY(12, 22.5);
$pdf->Cell(20, 3, $patient['patient_mrn'], 0, 1, 'L');

$pdf->SetFont('helvetica', 'B', 6);
$pdf->SetXY(32, 22.5);
$pdf->Cell(12, 3, 'AGE:', 0, 0, 'L');
$pdf->SetFont('helvetica', '', 6);
$pdf->SetXY(39, 22.5);
$pdf->Cell(8, 3, $age ? $age . 'y' : 'N/A', 0, 1, 'L');

$pdf->SetFont('helvetica', 'B', 6);
$pdf->SetXY(47, 22.5);
$pdf->Cell(15, 3, 'GENDER:', 0, 0, 'L');
$pdf->SetFont('helvetica', '', 6);
$pdf->SetXY(58, 22.5);
$pdf->Cell(8, 3, $patient['patient_gender'] ? substr($patient['patient_gender'], 0, 1) : 'N/A', 0, 1, 'L');

$pdf->SetFont('helvetica', 'B', 6);
$pdf->SetXY(3, 25.5);
$pdf->Cell(18, 3, 'ID NO:', 0, 0, 'L');
$pdf->SetFont('helvetica', '', 6);
$pdf->SetXY(18, 25.5);
$pdf->Cell(10, 3, $patient['patient_id_number'] ?: 'N/A', 0, 1, 'L');

$pdf->SetFont('helvetica', 'B', 6);
$pdf->SetXY(28, 25.5);
$pdf->Cell(18, 3, 'ALLERGIES:', 0, 0, 'L');
$pdf->SetFont('helvetica', '', 6);
$pdf->SetXY(42, 25.5);
//$pdf->Cell(40, 3, truncateText($patient['patient_allergies'] ?: 'None', 25), 0, 1, 'L');

// Emergency instructions
$pdf->SetFillColor(255, 240, 240);
$pdf->Rect(1, 29, 84, 6, 'F');
$pdf->SetTextColor(200, 0, 0);
$pdf->SetFont('helvetica', 'B', 5);
$pdf->SetXY(3, 30);
$pdf->MultiCell(80, 3, "IN EMERGENCY: PRESENT BOTH CARDS • CONTACT FACILITY IMMEDIATELY", 0, 'C');

// Authorization section
$pdf->SetFillColor(255, 255, 240);
$pdf->Rect(1, 35, 84, 5, 'F');
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('helvetica', 'B', 3);
$pdf->SetXY(3, 36);
$pdf->MultiCell(80, 2, "This card authorizes the bearer to make medical decisions for the patient in emergency situations.", 0, 'C');

// Footer with facility info
$pdf->SetFillColor(41, 128, 185);
$pdf->Rect(1, 40, 84, 4, 'F');
$pdf->SetTextColor(255, 255, 255);
$pdf->SetFont('helvetica', 'B', 3);
$pdf->SetXY(1, 40.5);
$pdf->Cell(84, 3, $session_company_name, 0, 1, 'C');

$pdf->SetTextColor(100, 100, 100);
$pdf->SetFont('helvetica', 'I', 5);
$pdf->SetXY(1, 44.5);
$pdf->Cell(84, 2, 'Issued: ' . date('m/d/Y'), 0, 1, 'C');
$pdf->SetXY(1, 47);
//$pdf->Cell(84, 2, 'Emergency: ' . ($session_company_phone ?: 'N/A'), 0, 1, 'C');

// Barcode area for guardian card
$pdf->SetFillColor(245, 245, 245);
$pdf->Rect(60, 44, 22, 8, 'F');
$pdf->SetTextColor(150, 150, 150);
$pdf->SetFont('helvetica', '', 4);
$pdf->SetXY(60, 47);
$pdf->Cell(22, 2, 'GUARDIAN ID', 0, 1, 'C');

// Close and output PDF document
$pdf->Output('patient_guardian_cards_' . $patient['patient_mrn'] . '.pdf', 'I');
exit;