<?php
// Start output buffering at the VERY beginning
if (ob_get_level()) ob_end_clean();
ob_start();

error_reporting(E_ALL);
ini_set('display_errors', 1);

// Get invoice ID first
$invoice_id = isset($_GET['invoice_id']) ? intval($_GET['invoice_id']) : 0;

if ($invoice_id == 0) {
    // Clean buffer and show error
    ob_clean();
    die('Invalid invoice ID');
}

// Now include files after basic validation
require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/inc_all.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/plugins/TCPDF/tcpdf.php';

// Clean any output that might have been generated by included files
ob_clean();

try {
    // Get hospital details
    $hospital_stmt = $mysqli->prepare("
        SELECT company_name, company_address, company_city, company_state, 
               company_zip, company_country, company_phone_country_code, 
               company_phone, company_email, company_website, company_logo,
               company_tax_id
        FROM companies 
        LIMIT 1
    ");
    
    if (!$hospital_stmt) {
        throw new Exception("Hospital database error: " . $mysqli->error);
    }
    
    if (!$hospital_stmt->execute()) {
        throw new Exception("Hospital execute failed: " . $hospital_stmt->error);
    }
    
    $hospital_result = $hospital_stmt->get_result();
    $hospital = $hospital_result->fetch_assoc();
    $hospital_stmt->close();

    // Fetch invoice details with new table structure
    $invoice_sql = "SELECT 
        i.*,
        p.patient_id,
        p.patient_first_name,
        p.patient_last_name,
        p.patient_phone,
        p.patient_email,
        p.patient_dob,
        p.patient_gender,
        CONCAT(p.patient_first_name, ' ', p.patient_last_name) as patient_name,
        v.visit_date,
        v.visit_id,
        v.visit_type,
        u.user_name as created_by_name,
        pb.pending_bill_id,
        pb.pending_bill_number,
        pl.price_list_name,
        pl.price_list_type,
        doc.user_name as doctor_name
    FROM invoices i 
    LEFT JOIN patients p ON i.patient_id = p.patient_id
    LEFT JOIN visits v ON i.visit_id = v.visit_id
    LEFT JOIN users u ON i.created_by = u.user_id
    LEFT JOIN pending_bills pb ON i.pending_bill_id = pb.pending_bill_id
    LEFT JOIN price_lists pl ON i.price_list_id = pl.price_list_id
    LEFT JOIN users doc ON v.visit_doctor_id = doc.user_id
    WHERE i.invoice_id = ?
    LIMIT 1";
    
    $invoice_stmt = $mysqli->prepare($invoice_sql);
    
    if (!$invoice_stmt) {
        throw new Exception("Invoice prepare failed: " . $mysqli->error);
    }
    
    $invoice_stmt->bind_param("i", $invoice_id);
    
    if (!$invoice_stmt->execute()) {
        throw new Exception("Invoice execute failed: " . $invoice_stmt->error);
    }
    
    $invoice_result = $invoice_stmt->get_result();

    if ($invoice_result->num_rows === 0) {
        throw new Exception("Invoice not found");
    }

    $invoice = $invoice_result->fetch_assoc();
    $invoice_stmt->close();

    // Check if visit has insurance coverage
    $insurance_coverage = null;
    $has_insurance = false;
    
    if ($invoice['visit_id']) {
        $insurance_sql = "SELECT 
            vi.*,
            ic.company_name,
            ic.phone,
            ic.email,
            isc.scheme_name,
            isc.scheme_code
        FROM visit_insurance vi
        LEFT JOIN insurance_companies ic ON vi.insurance_company_id = ic.insurance_company_id
        LEFT JOIN insurance_schemes isc ON vi.insurance_scheme_id = isc.scheme_id
        WHERE vi.visit_id = ? AND vi.is_primary = 1
        LIMIT 1";
        
        $insurance_stmt = $mysqli->prepare($insurance_sql);
        
        if ($insurance_stmt) {
            $insurance_stmt->bind_param("i", $invoice['visit_id']);
            
            if ($insurance_stmt->execute()) {
                $insurance_result = $insurance_stmt->get_result();
                
                if ($insurance_result->num_rows > 0) {
                    $has_insurance = true;
                    $insurance_coverage = $insurance_result->fetch_assoc();
                }
            }
            $insurance_stmt->close();
        }
    }

    // Fetch invoice items from new table structure
    $items_sql = "SELECT 
        ii.*,
        bi.item_name,
        bi.item_description,
        bi.item_code,
        bi.item_type,
        pli.price_list_id,
        pli.is_taxable,
        pli.discount_allowed
    FROM invoice_items ii
    LEFT JOIN billable_items bi ON ii.billable_item_id = bi.billable_item_id
    LEFT JOIN price_list_items pli ON ii.price_list_item_id = pli.price_list_item_id
    WHERE ii.invoice_id = ?
    ORDER BY ii.invoice_item_id ASC";
    
    $items_stmt = $mysqli->prepare($items_sql);
    
    if (!$items_stmt) {
        throw new Exception("Items prepare failed: " . $mysqli->error);
    }
    
    $items_stmt->bind_param("i", $invoice_id);
    
    if (!$items_stmt->execute()) {
        throw new Exception("Items execute failed: " . $items_stmt->error);
    }
    
    $items_result = $items_stmt->get_result();
    $invoice_items = [];
    $subtotal = 0;
    $total_discount = 0;
    $total_tax = 0;
    $grand_total = 0;

    while ($item = $items_result->fetch_assoc()) {
        $invoice_items[] = $item;
        $subtotal += $item['subtotal'];
        $total_discount += $item['discount_amount'];
        $total_tax += $item['tax_amount'];
        $grand_total += $item['total_amount'];
    }
    $items_stmt->close();

    // Calculate totals using new column names
    $total_amount = $invoice['total_amount'];
    $subtotal_amount = $invoice['subtotal_amount'];
    $discount_amount = $invoice['discount_amount'];
    $tax_amount = $invoice['tax_amount'];

    // Get payments for this invoice using new table structure
    $payments_sql = "SELECT 
        p.*,
        u.user_name as created_by_name,
        ba.account_name as bank_account_name,
        ca.account_name as cash_account_name
    FROM payments p
    LEFT JOIN users u ON p.created_by = u.user_id
    LEFT JOIN accounts ba ON p.bank_account_id = ba.account_id
    LEFT JOIN accounts ca ON p.cash_account_id = ca.account_id
    WHERE p.invoice_id = ? AND p.status = 'posted'
    ORDER BY p.payment_date ASC";
    
    $payments_stmt = $mysqli->prepare($payments_sql);
    if (!$payments_stmt) {
        throw new Exception("Payments prepare failed: " . $mysqli->error);
    }
    
    $payments_stmt->bind_param("i", $invoice_id);
    if (!$payments_stmt->execute()) {
        throw new Exception("Payments execute failed: " . $payments_stmt->error);
    }
    
    $payments_result = $payments_stmt->get_result();
    
    $payments = [];
    $cash_total = 0;
    $insurance_total = 0;
    $card_total = 0;
    $mpesa_total = 0;
    $bank_total = 0;
    $check_total = 0;
    $total_paid = 0;

    while ($payment = $payments_result->fetch_assoc()) {
        $payments[] = $payment;
        $total_paid += $payment['payment_amount'];
        
        // Categorize payments by method
        $method = strtolower($payment['payment_method'] ?? '');
        switch ($method) {
            case 'cash':
                $cash_total += $payment['payment_amount'];
                break;
            case 'insurance':
                $insurance_total += $payment['payment_amount'];
                break;
            case 'credit_card':
                $card_total += $payment['payment_amount'];
                break;
            case 'mobile_money':
                $mpesa_total += $payment['payment_amount'];
                break;
            case 'bank_transfer':
                $bank_total += $payment['payment_amount'];
                break;
            case 'check':
                $check_total += $payment['payment_amount'];
                break;
            default:
                if (strpos($method, 'cash') !== false) {
                    $cash_total += $payment['payment_amount'];
                } elseif (strpos($method, 'insurance') !== false) {
                    $insurance_total += $payment['payment_amount'];
                } elseif (strpos($method, 'card') !== false) {
                    $card_total += $payment['payment_amount'];
                } elseif (strpos($method, 'mpesa') !== false || strpos($method, 'mobile') !== false) {
                    $mpesa_total += $payment['payment_amount'];
                } elseif (strpos($method, 'bank') !== false) {
                    $bank_total += $payment['payment_amount'];
                } elseif (strpos($method, 'check') !== false) {
                    $check_total += $payment['payment_amount'];
                } else {
                    $cash_total += $payment['payment_amount']; // Default to cash
                }
                break;
        }
    }
    $payments_stmt->close();

    $balance_due = $total_amount - $total_paid;

    // Calculate patient age
    $patient_age = '';
    if (!empty($invoice['patient_dob'])) {
        $birthDate = new DateTime($invoice['patient_dob']);
        $today = new DateTime();
        $age = $today->diff($birthDate)->y;
        $patient_age = "$age years";
    }

    // Build hospital address string
    $hospital_address = '';
    if (!empty($hospital['company_address'])) {
        $hospital_address = $hospital['company_address'];
        if (!empty($hospital['company_city'])) {
            $hospital_address .= ', ' . $hospital['company_city'];
        }
        if (!empty($hospital['company_state'])) {
            $hospital_address .= ', ' . $hospital['company_state'];
        }
        if (!empty($hospital['company_zip'])) {
            $hospital_address .= ' ' . $hospital['company_zip'];
        }
        if (!empty($hospital['company_country'])) {
            $hospital_address .= ', ' . $hospital['company_country'];
        }
    }

    // Build hospital phone string
    $hospital_phone = '';
    if (!empty($hospital['company_phone'])) {
        $hospital_phone = $hospital['company_phone'];
        if (!empty($hospital['company_phone_country_code'])) {
            $hospital_phone = '+' . $hospital['company_phone_country_code'] . ' ' . $hospital_phone;
        }
    }

    // Format dates
    $invoice_date = date('F j, Y', strtotime($invoice['invoice_date']));
    $due_date = $invoice['due_date'] ? date('F j, Y', strtotime($invoice['due_date'])) : 'Immediate';
    $visit_date = $invoice['visit_date'] ? date('m/d/Y', strtotime($invoice['visit_date'])) : 'N/A';

    // Create new PDF document
    $pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);

    // Set document information
    $pdf->SetCreator($hospital['company_name'] ?? 'Hospital Management System');
    $pdf->SetAuthor($hospital['company_name'] ?? 'Hospital');
    $pdf->SetTitle('Medical Invoice #' . $invoice['invoice_number']);
    $pdf->SetSubject('Medical Invoice');

    // Remove default header/footer
    $pdf->setPrintHeader(false);
    $pdf->setPrintFooter(false);

    // Set margins
    $pdf->SetMargins(15, 15, 15);
    $pdf->SetAutoPageBreak(TRUE, 15);

    // Add a page
    $pdf->AddPage();

    // Add medical watermark
    $pdf->SetAlpha(0.1);
    $pdf->SetFont('helvetica', 'B', 120);
    $pdf->SetTextColor(200, 200, 200);
    
    // Save current position and rotate
    $pdf->StartTransform();
    $pdf->Rotate(45, 105, 150);
    $pdf->Text(30, 100, 'MEDICAL');
    $pdf->StopTransform();
    
    // RESET everything properly after rotation
    $pdf->SetAlpha(1);
    $pdf->SetTextColor(0, 0, 0);
    $pdf->SetFont('helvetica', '', 10);
    
    // Reset to top of page for content
    $pdf->SetY(15);

    // Header with hospital info
    $pdf->SetFont('helvetica', 'B', 16);
    $pdf->Cell(0, 8, 'MEDICAL INVOICE', 0, 1, 'C');
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->Cell(0, 6, $hospital['company_name'] ?? 'MEDICAL CENTER', 0, 1, 'C');
    $pdf->SetFont('helvetica', '', 10);
    
    // Hospital address
    if (!empty($hospital_address)) {
        $pdf->Cell(0, 5, $hospital_address, 0, 1, 'C');
    }
    
    // Hospital contact info
    $contact_info = '';
    if (!empty($hospital_phone)) {
        $contact_info .= 'Phone: ' . $hospital_phone;
    }
    if (!empty($hospital['company_email'])) {
        if (!empty($contact_info)) $contact_info .= ' | ';
        $contact_info .= 'Email: ' . $hospital['company_email'];
    }
    if (!empty($hospital['company_website'])) {
        if (!empty($contact_info)) $contact_info .= ' | ';
        $contact_info .= 'Web: ' . $hospital['company_website'];
    }
    
    if (!empty($contact_info)) {
        $pdf->Cell(0, 5, $contact_info, 0, 1, 'C');
    }
    
    // Medical credentials
    $credentials = [];
    if (!empty($hospital['company_license_number'])) {
        $credentials[] = 'License: ' . $hospital['company_license_number'];
    }
    if (!empty($hospital['company_tax_id'])) {
        $credentials[] = 'Tax ID: ' . $hospital['company_tax_id'];
    }
    
    if (!empty($credentials)) {
        $pdf->Cell(0, 5, implode(' | ', $credentials), 0, 1, 'C');
    }
    
    $pdf->Ln(8);

    // Invoice header
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->Cell(0, 6, 'INVOICE #' . $invoice['invoice_number'], 0, 1, 'L');
    $pdf->SetFont('helvetica', '', 10);
    $pdf->Cell(0, 5, 'Date: ' . $invoice_date, 0, 1, 'L');
    $pdf->Cell(0, 5, 'Due Date: ' . $due_date, 0, 1, 'L');
    
    // Show payment type indicator
    if ($has_insurance) {
        $pdf->SetTextColor(0, 128, 0); // Green for insurance
        $pdf->Cell(0, 5, 'Payment Type: INSURANCE COVERED', 0, 1, 'L');
    } else {
        $pdf->SetTextColor(198, 40, 40); // Red for cash/self-pay
        $pdf->Cell(0, 5, 'Payment Type: PATIENT SELF-PAY', 0, 1, 'L');
    }
    $pdf->SetTextColor(0, 0, 0);
    
    if (!empty($invoice['pending_bill_number'])) {
        $pdf->Cell(0, 5, 'Bill Reference: #' . $invoice['pending_bill_number'], 0, 1, 'L');
    }
    
    $pdf->Ln(5);

    // Patient and Billing information in two columns - LIKE PRESCRIPTION STYLE
    $pdf->SetFont('helvetica', 'B', 11);
    $pdf->SetFillColor(240, 240, 240);
    $pdf->Cell(95, 7, 'PATIENT INFORMATION', 1, 0, 'C', true);
    $pdf->Cell(95, 7, 'BILLING INFORMATION', 1, 1, 'C', true);
    
    $pdf->SetFont('helvetica', '', 9);
    
    // Patient column
    $pdf->Cell(95, 6, 'Name: ' . $invoice['patient_name'], 1, 0, 'L');
    $pdf->Cell(95, 6, 'Invoice #: ' . $invoice['invoice_number'], 1, 1, 'L');
    
    $pdf->Cell(95, 6, 'Patient ID: ' . $invoice['patient_identifier'], 1, 0, 'L');
    $pdf->Cell(95, 6, 'Status: ' . ucfirst(str_replace('_', ' ', $invoice['invoice_status'])), 1, 1, 'L');
    
    $pdf->Cell(95, 6, 'Age: ' . $patient_age, 1, 0, 'L');
    $pdf->Cell(95, 6, 'Price List: ' . $invoice['price_list_name'], 1, 1, 'L');
    
    $pdf->Cell(95, 6, 'Gender: ' . $invoice['patient_gender'], 1, 0, 'L');
    $pdf->Cell(95, 6, 'Rate Type: ' . ucfirst($invoice['price_list_type']), 1, 1, 'L');
    
    if (!empty($invoice['patient_dob'])) {
        $pdf->Cell(95, 6, 'DOB: ' . date('m/d/Y', strtotime($invoice['patient_dob'])), 1, 0, 'L');
    } else {
        $pdf->Cell(95, 6, '', 1, 0, 'L');
    }
    $pdf->Cell(95, 6, 'Visit Date: ' . $visit_date, 1, 1, 'L');
    
    // Contact information
    if (!empty($invoice['patient_phone'])) {
        $pdf->Cell(95, 6, 'Phone: ' . $invoice['patient_phone'], 1, 0, 'L');
    } else {
        $pdf->Cell(95, 6, '', 1, 0, 'L');
    }
    $pdf->Cell(95, 6, 'Provider: ' . ($invoice['doctor_name'] ?? 'N/A'), 1, 1, 'L');
    
    // Insurance information if available
    if ($has_insurance && $insurance_coverage) {
        $pdf->Cell(190, 7, 'INSURANCE COVERAGE DETAILS', 1, 1, 'C', true);
        $pdf->SetFont('helvetica', 'B', 9);
        
        $pdf->Cell(95, 6, 'Insurance Company: ' . $insurance_coverage['insurance_company_name'], 1, 0, 'L');
        $pdf->Cell(95, 6, 'Scheme: ' . ($insurance_coverage['scheme_name'] ?? 'N/A'), 1, 1, 'L');
        
        $pdf->SetFont('helvetica', '', 9);
        $pdf->Cell(95, 6, 'Member #: ' . $insurance_coverage['member_number'], 1, 0, 'L');
        $pdf->Cell(95, 6, 'Coverage: ' . $insurance_coverage['coverage_percentage'] . '%', 1, 1, 'L');
        
        if (!empty($insurance_coverage['authorization_code'])) {
            $pdf->Cell(95, 6, 'Auth Code: ' . $insurance_coverage['authorization_code'], 1, 0, 'L');
        } else {
            $pdf->Cell(95, 6, '', 1, 0, 'L');
        }
        
        if (!empty($insurance_coverage['insurance_company_phone'])) {
            $pdf->Cell(95, 6, 'Ins. Phone: ' . $insurance_coverage['insurance_company_phone'], 1, 1, 'L');
        } else {
            $pdf->Cell(95, 6, '', 1, 1, 'L');
        }
    } else {
        // Show self-pay indicator
        $pdf->Cell(190, 7, 'SELF-PAY PATIENT', 1, 1, 'C', true);
        $pdf->Cell(190, 6, 'No insurance coverage - Patient is responsible for full payment', 1, 1, 'C');
    }
    
    $pdf->Ln(8);

    // Medical Services header
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->SetFillColor(240, 240, 240);
    $pdf->Cell(0, 7, 'MEDICAL SERVICES & CHARGES', 0, 1, 'L', true);
    $pdf->Ln(3);

    // Services table header - PROFESSIONAL ALIGNMENT LIKE PRESCRIPTION
    $pdf->SetFont('helvetica', 'B', 9);
    $pdf->SetFillColor(220, 220, 220);
    $pdf->Cell(15, 7, '#', 1, 0, 'C', true);
    $pdf->Cell(65, 7, 'Service Description', 1, 0, 'C', true);
    $pdf->Cell(25, 7, 'Code', 1, 0, 'C', true);
    $pdf->Cell(20, 7, 'Qty', 1, 0, 'C', true);
    $pdf->Cell(30, 7, 'Unit Price', 1, 0, 'C', true);
    $pdf->Cell(35, 7, 'Amount', 1, 1, 'C', true);

    // Services content
    $pdf->SetFont('helvetica', '', 8);
    if (!empty($invoice_items)) {
        foreach ($invoice_items as $index => $item) {
            $item_number = $index + 1;
            $description = $item['item_name'];
            if (!empty($item['item_description'])) {
                $description .= "\n" . substr($item['item_description'], 0, 50) . (strlen($item['item_description']) > 50 ? '...' : '');
            }
            
            $procedure_code = !empty($item['item_code']) ? $item['item_code'] : 'N/A';
            $quantity = $item['item_quantity'];
            $unit_price = $item['unit_price'];
            $line_total = $item['total_amount'];
            
            // Calculate height for multi-line description
            $desc_height = max($pdf->getStringHeight(65, $description, false, true, '', 1), 10);
            
            $pdf->MultiCell(15, $desc_height, $item_number, 1, 'C', false, 0);
            $pdf->MultiCell(65, $desc_height, $description, 1, 'L', false, 0);
            $pdf->MultiCell(25, $desc_height, $procedure_code, 1, 'C', false, 0);
            $pdf->MultiCell(20, $desc_height, number_format($quantity, 2), 1, 'C', false, 0);
            $pdf->MultiCell(30, $desc_height, 'KSH ' . number_format($unit_price, 2), 1, 'R', false, 0);
            $pdf->MultiCell(35, $desc_height, 'KSH ' . number_format($line_total, 2), 1, 'R', false, 1);
            
            // Add item details if available
            if ($item['discount_amount'] > 0 || $item['tax_amount'] > 0) {
                $detail_height = 4;
                $pdf->SetFont('helvetica', 'I', 7);
                $pdf->Cell(15, $detail_height, '', 0, 0);
                $pdf->Cell(65, $detail_height, '', 0, 0);
                
                $details = [];
                if ($item['discount_amount'] > 0) {
                    $discount_percent = $item['discount_percentage'] > 0 ? " ({$item['discount_percentage']}%)" : '';
                    $details[] = 'Discount: KSH ' . number_format($item['discount_amount'], 2) . $discount_percent;
                }
                if ($item['tax_amount'] > 0) {
                    $tax_percent = $item['tax_percentage'] > 0 ? " ({$item['tax_percentage']}%)" : '';
                    $details[] = 'Tax: KSH ' . number_format($item['tax_amount'], 2) . $tax_percent;
                }
                
                if (!empty($details)) {
                    $pdf->Cell(25, $detail_height, '', 0, 0);
                    $pdf->Cell(20, $detail_height, '', 0, 0);
                    $pdf->Cell(30, $detail_height, '', 0, 0);
                    $pdf->Cell(35, $detail_height, implode(', ', $details), 0, 1, 'R');
                }
                $pdf->SetFont('helvetica', '', 8);
            }
        }
    } else {
        $pdf->Cell(190, 30, 'No items found', 1, 1, 'C');
    }

    $pdf->Ln(8);

    // Calculate insurance coverage if applicable
    $insurance_payable = 0;
    $patient_portion = 0;
    
    if ($has_insurance && $insurance_coverage) {
        $coverage_percentage = floatval($insurance_coverage['coverage_percentage']);
        $insurance_payable = ($total_amount * $coverage_percentage) / 100;
        $patient_portion = $total_amount - $insurance_payable;
    }

    // Financial Summary - RIGHT ALIGNED PROFESSIONALLY
    $summary_width = 50;
    $value_width = 40;
    $indent_width = 100;

    $pdf->SetFont('helvetica', '', 10);
    
    // Subtotal
    $pdf->Cell($indent_width, 7, '', 0, 0);
    $pdf->Cell($summary_width, 7, 'Subtotal:', 0, 0, 'R');
    $pdf->SetFont('helvetica', 'B', 10);
    $pdf->Cell($value_width, 7, 'KSH ' . number_format($subtotal_amount, 2), 0, 1, 'R');
    $pdf->SetFont('helvetica', '', 10);

    // Discount
    if ($discount_amount > 0) {
        $pdf->Cell($indent_width, 7, '', 0, 0);
        $pdf->Cell($summary_width, 7, 'Discount:', 0, 0, 'R');
        $pdf->SetFont('helvetica', 'B', 10);
        $pdf->Cell($value_width, 7, '- KSH ' . number_format($discount_amount, 2), 0, 1, 'R');
        $pdf->SetFont('helvetica', '', 10);
    }

    // Tax
    if ($tax_amount > 0) {
        $pdf->Cell($indent_width, 7, '', 0, 0);
        $pdf->Cell($summary_width, 7, 'Tax:', 0, 0, 'R');
        $pdf->SetFont('helvetica', 'B', 10);
        $pdf->Cell($value_width, 7, 'KSH ' . number_format($tax_amount, 2), 0, 1, 'R');
        $pdf->SetFont('helvetica', '', 10);
    }

    // Total Amount
    $pdf->SetLineWidth(0.3);
    $pdf->Line($pdf->GetX() + $indent_width, $pdf->GetY(), $pdf->GetX() + $indent_width + $summary_width + $value_width, $pdf->GetY());
    $pdf->Cell($indent_width, 8, '', 0, 0);
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->SetTextColor(0, 0, 200);
    $pdf->Cell($summary_width, 8, 'TOTAL AMOUNT:', 0, 0, 'R');
    $pdf->Cell($value_width, 8, 'KSH ' . number_format($total_amount, 2), 0, 1, 'R');
    $pdf->SetTextColor(0, 0, 0);

    // Show insurance breakdown if applicable
    if ($has_insurance && $insurance_coverage) {
        $pdf->Ln(4);
        
        // Insurance Portion
        $pdf->Cell($indent_width, 7, '', 0, 0);
        $pdf->SetFont('helvetica', '', 10);
        $pdf->SetTextColor(0, 100, 0);
        $pdf->Cell($summary_width, 7, 'Insurance (' . $insurance_coverage['coverage_percentage'] . '%):', 0, 0, 'R');
        $pdf->SetFont('helvetica', 'B', 10);
        $pdf->Cell($value_width, 7, '- KSH ' . number_format($insurance_payable, 2), 0, 1, 'R');
        
        // Patient Portion
        $pdf->Cell($indent_width, 7, '', 0, 0);
        $pdf->SetFont('helvetica', '', 10);
        $pdf->SetTextColor(198, 40, 40);
        $pdf->Cell($summary_width, 7, 'Patient Portion:', 0, 0, 'R');
        $pdf->SetFont('helvetica', 'B', 10);
        $pdf->Cell($value_width, 7, 'KSH ' . number_format($patient_portion, 2), 0, 1, 'R');
        $pdf->SetTextColor(0, 0, 0);
    }

    // Payment Breakdown - RIGHT ALIGNED
    if ($total_paid > 0) {
        $pdf->SetFont('helvetica', '', 9);
        $pdf->Ln(4);
        
        // Insurance Payments
        if ($insurance_total > 0) {
            $pdf->Cell($indent_width, 6, '', 0, 0);
            $pdf->SetTextColor(0, 128, 0);
            $pdf->Cell($summary_width, 6, 'Insurance Paid:', 0, 0, 'R');
            $pdf->SetFont('helvetica', 'B', 9);
            $pdf->Cell($value_width, 6, '- KSH ' . number_format($insurance_total, 2), 0, 1, 'R');
            $pdf->SetTextColor(0, 0, 0);
            $pdf->SetFont('helvetica', '', 9);
        }
        
        // Cash Payments
        if ($cash_total > 0) {
            $pdf->Cell($indent_width, 6, '', 0, 0);
            $pdf->SetTextColor(0, 128, 0);
            $pdf->Cell($summary_width, 6, 'Cash Paid:', 0, 0, 'R');
            $pdf->SetFont('helvetica', 'B', 9);
            $pdf->Cell($value_width, 6, '- KSH ' . number_format($cash_total, 2), 0, 1, 'R');
            $pdf->SetTextColor(0, 0, 0);
            $pdf->SetFont('helvetica', '', 9);
        }
        
        // Card Payments
        if ($card_total > 0) {
            $pdf->Cell($indent_width, 6, '', 0, 0);
            $pdf->SetTextColor(0, 128, 0);
            $pdf->Cell($summary_width, 6, 'Card Paid:', 0, 0, 'R');
            $pdf->SetFont('helvetica', 'B', 9);
            $pdf->Cell($value_width, 6, '- KSH ' . number_format($card_total, 2), 0, 1, 'R');
            $pdf->SetTextColor(0, 0, 0);
            $pdf->SetFont('helvetica', '', 9);
        }
        
        // Mobile Money Payments
        if ($mpesa_total > 0) {
            $pdf->Cell($indent_width, 6, '', 0, 0);
            $pdf->SetTextColor(0, 128, 0);
            $pdf->Cell($summary_width, 6, 'Mobile Money:', 0, 0, 'R');
            $pdf->SetFont('helvetica', 'B', 9);
            $pdf->Cell($value_width, 6, '- KSH ' . number_format($mpesa_total, 2), 0, 1, 'R');
            $pdf->SetTextColor(0, 0, 0);
            $pdf->SetFont('helvetica', '', 9);
        }
        
        // Bank Transfer Payments
        if ($bank_total > 0) {
            $pdf->Cell($indent_width, 6, '', 0, 0);
            $pdf->SetTextColor(0, 128, 0);
            $pdf->Cell($summary_width, 6, 'Bank Transfer:', 0, 0, 'R');
            $pdf->SetFont('helvetica', 'B', 9);
            $pdf->Cell($value_width, 6, '- KSH ' . number_format($bank_total, 2), 0, 1, 'R');
            $pdf->SetTextColor(0, 0, 0);
            $pdf->SetFont('helvetica', '', 9);
        }
        
        // Check Payments
        if ($check_total > 0) {
            $pdf->Cell($indent_width, 6, '', 0, 0);
            $pdf->SetTextColor(0, 128, 0);
            $pdf->Cell($summary_width, 6, 'Check:', 0, 0, 'R');
            $pdf->SetFont('helvetica', 'B', 9);
            $pdf->Cell($value_width, 6, '- KSH ' . number_format($check_total, 2), 0, 1, 'R');
            $pdf->SetTextColor(0, 0, 0);
            $pdf->SetFont('helvetica', '', 9);
        }
        
        // Total Payments Line
        $pdf->SetLineWidth(0.3);
        $pdf->Line($pdf->GetX() + $indent_width, $pdf->GetY(), $pdf->GetX() + $indent_width + $summary_width + $value_width, $pdf->GetY());
        $pdf->Cell($indent_width, 7, '', 0, 0);
        $pdf->SetFont('helvetica', 'B', 10);
        $pdf->SetTextColor(0, 128, 0);
        $pdf->Cell($summary_width, 7, 'TOTAL PAYMENTS:', 0, 0, 'R');
        $pdf->Cell($value_width, 7, '- KSH ' . number_format($total_paid, 2), 0, 1, 'R');
        $pdf->SetTextColor(0, 0, 0);
    }

    // Balance Due
    $pdf->SetLineWidth(0.5);
    $pdf->Line($pdf->GetX() + $indent_width, $pdf->GetY(), $pdf->GetX() + $indent_width + $summary_width + $value_width, $pdf->GetY());
    $pdf->Ln(4);
    
    $pdf->Cell($indent_width, 8, '', 0, 0);
    $pdf->SetFont('helvetica', 'B', 12);
    
    if ($balance_due > 0) {
        $pdf->SetTextColor(198, 40, 40); // Red for balance due
    } else {
        $pdf->SetTextColor(0, 128, 0); // Green for paid in full
    }
    
    $pdf->Cell($summary_width, 8, 'BALANCE DUE:', 0, 0, 'R');
    $pdf->Cell($value_width, 8, 'KSH ' . number_format($balance_due, 2), 0, 1, 'R');
    $pdf->SetTextColor(0, 0, 0);

    $pdf->Ln(12);

    // Payment Terms and Notes
    if (!empty($invoice['payment_terms'])) {
        $pdf->SetFont('helvetica', 'B', 9);
        $pdf->SetTextColor(0, 0, 150);
        $pdf->Cell(0, 6, 'Payment Terms: ' . $invoice['payment_terms'], 0, 1, 'L');
        $pdf->SetTextColor(0, 0, 0);
    }
    
    // Show insurance-specific notes if applicable
    if ($has_insurance) {
        $pdf->SetFont('helvetica', 'I', 9);
        $pdf->SetTextColor(0, 100, 0);
        $pdf->MultiCell(0, 6, 'Note: This invoice is covered by insurance. Please submit to ' . 
                      $insurance_coverage['insurance_company_name'] . 
                      ' for processing. Patient portion is due upon receipt.', 0, 'L');
        $pdf->SetTextColor(0, 0, 0);
    } else if (!empty($invoice['notes'])) {
        $pdf->SetFont('helvetica', '', 9);
        $pdf->MultiCell(0, 6, 'Notes: ' . $invoice['notes'], 0, 'L');
    }

    // Important billing information
    $pdf->SetFont('helvetica', 'B', 9);
    $pdf->SetTextColor(255, 0, 0);
    
    if ($has_insurance) {
        $pdf->Cell(0, 6, 'IMPORTANT: Insurance claims must be submitted within 30 days. Patient portion is due immediately.', 0, 1, 'C');
    } else {
        $pdf->Cell(0, 6, 'IMPORTANT: Payment is due upon receipt. Please contact billing department with any questions.', 0, 1, 'C');
    }
    
    $pdf->SetTextColor(0, 0, 0);

    $pdf->Ln(8);

    // Signature area
    $pdf->SetFont('helvetica', 'B', 10);
    $pdf->Cell(0, 5, 'Authorized Signature:', 0, 1, 'L');
    $pdf->Ln(8);
    
    // Signature line
    $pdf->Line(20, $pdf->GetY(), 80, $pdf->GetY());
    $pdf->SetFont('helvetica', '', 9);
    $pdf->Cell(60, 5, $hospital['company_name'] ?? 'Medical Center', 0, 0, 'L');
    $pdf->Cell(0, 5, date('m/d/Y'), 0, 1, 'R');
    
    $pdf->Ln(8);
    
    // System Information
    $pdf->SetFont('helvetica', 'I', 8);
    $pdf->SetTextColor(100, 100, 100);
    $pdf->Cell(0, 4, 'Invoice Created: ' . date('F j, Y \a\t g:i A', strtotime($invoice['created_at'])), 0, 1, 'L');
    $pdf->Cell(0, 4, 'Created By: ' . ($invoice['created_by_name'] ?? 'System'), 0, 1, 'L');
    if ($invoice['finalized_at']) {
        $pdf->Cell(0, 4, 'Finalized: ' . date('F j, Y \a\t g:i A', strtotime($invoice['finalized_at'])), 0, 1, 'L');
    }
    
    $pdf->Ln(4);
    
    // Payment type summary
    $pdf->SetFont('helvetica', 'B', 8);
    if ($has_insurance) {
        $pdf->SetTextColor(0, 100, 0);
        $pdf->Cell(0, 4, 'INVOICE TYPE: INSURANCE BILLING', 0, 1, 'C');
    } else {
        $pdf->SetTextColor(198, 40, 40);
        $pdf->Cell(0, 4, 'INVOICE TYPE: SELF-PAY / CASH BILLING', 0, 1, 'C');
    }
    
    $pdf->Ln(2);
    
    // Footer with hospital info
    $pdf->SetFont('helvetica', 'I', 8);
    $pdf->SetTextColor(128, 128, 128);
    $pdf->Cell(0, 4, 'This is a computer-generated invoice from ' . ($hospital['company_name'] ?? 'Medical Center') . '.', 0, 1, 'C');
    $pdf->Cell(0, 4, 'For billing inquiries, please contact our accounts department.', 0, 1, 'C');
    $pdf->Cell(0, 4, 'Document generated on: ' . date('F j, Y \a\t g:i A'), 0, 1, 'C');

    // Clean output buffer completely before sending PDF
    ob_clean();
    
    // Output PDF
    $pdf->Output('medical_invoice_' . $invoice['invoice_number'] . '.pdf', 'I');
    exit;
    
} catch (Exception $e) {
    // Clean buffer and show error
    ob_clean();
    die('PDF Generation Error: ' . $e->getMessage());
}