<?php
// Enable full error reporting for debugging
error_reporting(E_ALL);
ini_set('display_errors', 1);

if (ob_get_level()) ob_end_clean();
ob_start();


// Get the document root and include the main file
$doc_root = $_SERVER['DOCUMENT_ROOT'];
require_once $doc_root . '/includes/inc_all.php';
// Clean any output that might have been generated by included files
ob_clean();
// Set headers for JSON response
header('Content-Type: application/json');

try {
    // Check if user has permission to view files
    if (!SimplePermission::any(['patient_files_view', '*'])) {
        throw new Exception('You do not have permission to view file details.');
    }

    // Get file_id from GET parameter
    $file_id = isset($_GET['file_id']) ? intval($_GET['file_id']) : 0;

    if ($file_id <= 0) {
        throw new Exception('Invalid file ID.');
    }

    // Query to get detailed file information
    $sql = "
        SELECT 
            pf.*,
            p.patient_id,
            p.patient_first_name,
            p.patient_middle_name,
            p.patient_last_name,
            p.patient_mrn,
            p.patient_dob,
            p.patient_gender,
            p.patient_phone,
            p.patient_mobile,
            p.patient_email,
            u.user_name as uploaded_by_name,
            u.user_email as uploaded_by_email,
            ub.user_name as archived_by_name,
            v.visit_id,
            v.visit_type,
            v.visit_date,
            v.visit_status,
            d.department_name,
            doctor.user_name as doctor_name
        FROM patient_files pf
        LEFT JOIN patients p ON pf.file_patient_id = p.patient_id
        LEFT JOIN users u ON pf.file_uploaded_by = u.user_id
        LEFT JOIN users ub ON pf.file_archived_by = ub.user_id
        LEFT JOIN visits v ON pf.file_visit_id = v.visit_id
        LEFT JOIN departments d ON v.visit_department_id = d.department_id
        LEFT JOIN users doctor ON v.visit_doctor_id = doctor.user_id
        WHERE pf.file_id = ?
        AND pf.file_archived_at IS NULL
    ";
    
    $stmt = $mysqli->prepare($sql);
    if (!$stmt) {
        throw new Exception('Failed to prepare SQL statement: ' . $mysqli->error);
    }
    
    $stmt->bind_param("i", $file_id);
    
    if (!$stmt->execute()) {
        throw new Exception('Failed to execute SQL statement: ' . $stmt->error);
    }
    
    $result = $stmt->get_result();
    
    if ($result->num_rows === 0) {
        throw new Exception('File not found or has been archived. File ID: ' . $file_id);
    }
    
    $file = $result->fetch_assoc();
    
    // Format the data for display
    $response = [
        'success' => true,
        'html' => generateFileDetailsHTML($file)
    ];
    
    echo json_encode($response);
    
} catch (Exception $e) {
    $error_response = [
        'success' => false,
        'error' => $e->getMessage()
    ];
    
    echo json_encode($error_response);
}

/**
 * Generate HTML for file details modal
 */
function generateFileDetailsHTML($file) {
    // Calculate patient age
    $patient_age = '';
    if (!empty($file['patient_dob'])) {
        $birthDate = new DateTime($file['patient_dob']);
        $today = new DateTime();
        $age = $today->diff($birthDate)->y;
        $patient_age = " ($age yrs)";
    }
    
    // Build patient full name
    $patient_full_name = $file['patient_first_name'];
    if (!empty($file['patient_middle_name'])) {
        $patient_full_name .= ' ' . $file['patient_middle_name'];
    }
    $patient_full_name .= ' ' . $file['patient_last_name'];
    
    // Get file icon
    $file_icon = getFileIcon($file['file_type']);
    
    // Format file size
    $file_size = formatBytes($file['file_size']);
    
    // Format dates
    $upload_date = date('F j, Y g:i A', strtotime($file['file_uploaded_at']));
    $upload_date_relative = time_elapsed_string($file['file_uploaded_at']);
    
    // Visibility badge
    $visibility_badge = getVisibilityBadge($file['file_visibility']);
    
    $html = '
    <div class="row">
        <div class="col-md-12">
            <!-- File Header -->
            <div class="text-center mb-4">
                <i class="fas fa-' . $file_icon . ' fa-4x text-primary mb-3"></i>
                <h4 class="font-weight-bold">' . htmlspecialchars($file['file_original_name']) . '</h4>
                <p class="text-muted">' . strtoupper($file['file_type']) . ' • ' . $file_size . '</p>
            </div>
            
            <!-- File Information -->
            <div class="card mb-4">
                <div class="card-header bg-light">
                    <h5 class="card-title mb-0"><i class="fas fa-info-circle mr-2"></i>File Information</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <table class="table table-sm table-borderless">
                                <tr>
                                    <td class="text-muted" width="40%">Category:</td>
                                    <td><span class="badge badge-secondary">' . htmlspecialchars($file['file_category']) . '</span></td>
                                </tr>
                                <tr>
                                    <td class="text-muted">Visibility:</td>
                                    <td>' . $visibility_badge . '</td>
                                </tr>
                                <tr>
                                    <td class="text-muted">Uploaded:</td>
                                    <td>' . $upload_date . '<br><small class="text-muted">(' . $upload_date_relative . ')</small></td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-md-6">
                            <table class="table table-sm table-borderless">
                                <tr>
                                    <td class="text-muted" width="40%">File Type:</td>
                                    <td>' . strtoupper($file['file_type']) . '</td>
                                </tr>
                                <tr>
                                    <td class="text-muted">File Size:</td>
                                    <td>' . $file_size . '</td>
                                </tr>
                                <tr>
                                    <td class="text-muted">Uploaded By:</td>
                                    <td>' . htmlspecialchars($file['uploaded_by_name']) . '</td>
                                </tr>
                            </table>
                        </div>
                    </div>';

    // File description
    if (!empty($file['file_description'])) {
        $html .= '
                    <div class="row mt-3">
                        <div class="col-12">
                            <strong class="text-muted">Description:</strong>
                            <p class="mt-1">' . nl2br(htmlspecialchars($file['file_description'])) . '</p>
                        </div>
                    </div>';
    }
    
    $html .= '
                </div>
            </div>
            
            <!-- Patient Information -->
            <div class="card mb-4">
                <div class="card-header bg-light">
                    <h5 class="card-title mb-0"><i class="fas fa-user-injured mr-2"></i>Patient Information</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <table class="table table-sm table-borderless">
                                <tr>
                                    <td class="text-muted" width="40%">Patient:</td>
                                    <td>
                                        <strong>' . htmlspecialchars($patient_full_name) . $patient_age . '</strong><br>
                                        <small class="text-muted">MRN: ' . htmlspecialchars($file['patient_mrn']) . '</small>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-muted">Gender:</td>
                                    <td>' . (!empty($file['patient_gender']) ? htmlspecialchars($file['patient_gender']) : 'Not specified') . '</td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-md-6">
                            <table class="table table-sm table-borderless">';

    if (!empty($file['patient_phone']) || !empty($file['patient_mobile'])) {
        $html .= '
                                <tr>
                                    <td class="text-muted" width="40%">Contact:</td>
                                    <td>';
        if (!empty($file['patient_phone'])) {
            $html .= htmlspecialchars($file['patient_phone']) . ' <small class="text-muted">(Phone)</small><br>';
        }
        if (!empty($file['patient_mobile'])) {
            $html .= htmlspecialchars($file['patient_mobile']) . ' <small class="text-muted">(Mobile)</small>';
        }
        $html .= '
                                    </td>
                                </tr>';
    }
    
    if (!empty($file['patient_email'])) {
        $html .= '
                                <tr>
                                    <td class="text-muted">Email:</td>
                                    <td>' . htmlspecialchars($file['patient_email']) . '</td>
                                </tr>';
    }
    
    $html .= '
                            </table>
                        </div>
                    </div>
                </div>
            </div>';

    // Visit Information (if associated with a visit)
    if (!empty($file['visit_id'])) {
        $visit_date = date('F j, Y g:i A', strtotime($file['visit_date']));
        $html .= '
            <!-- Visit Information -->
            <div class="card mb-4">
                <div class="card-header bg-light">
                    <h5 class="card-title mb-0"><i class="fas fa-calendar-check mr-2"></i>Associated Visit</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <table class="table table-sm table-borderless">
                                <tr>
                                    <td class="text-muted" width="40%">Visit ID:</td>
                                    <td>#' . $file['visit_id'] . '</td>
                                </tr>
                                <tr>
                                    <td class="text-muted">Type:</td>
                                    <td><span class="badge badge-info">' . htmlspecialchars($file['visit_type']) . '</span></td>
                                </tr>
                                <tr>
                                    <td class="text-muted">Date:</td>
                                    <td>' . $visit_date . '</td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-md-6">
                            <table class="table table-sm table-borderless">';
        
        if (!empty($file['doctor_name'])) {
            $html .= '
                                <tr>
                                    <td class="text-muted" width="40%">Doctor:</td>
                                    <td>' . htmlspecialchars($file['doctor_name']) . '</td>
                                </tr>';
        }
        
        if (!empty($file['department_name'])) {
            $html .= '
                                <tr>
                                    <td class="text-muted">Department:</td>
                                    <td>' . htmlspecialchars($file['department_name']) . '</td>
                                </tr>';
        }
        
        if (!empty($file['visit_status'])) {
            $status_badge = getVisitStatusBadge($file['visit_status']);
            $html .= '
                                <tr>
                                    <td class="text-muted">Status:</td>
                                    <td>' . $status_badge . '</td>
                                </tr>';
        }
        
        $html .= '
                            </table>
                        </div>
                    </div>
                </div>
            </div>';
    }
    
    // File Actions
    $html .= '
            <!-- Actions -->
            <div class="card">
                <div class="card-header bg-light">
                    <h5 class="card-title mb-0"><i class="fas fa-cogs mr-2"></i>Actions</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">';

    if (true) { // For testing - replace with permission check
        $html .= '
                            <a href="/clinic/patient/download_file.php?file_id=' . $file['file_id'] . '" 
                               class="btn btn-primary btn-sm mr-2">
                                <i class="fas fa-download mr-1"></i>Download File
                            </a>';
    }
    
    if (true) { // For testing - replace with permission check
        $html .= '
                            <a href="/clinic/patient/patient_details.php?patient_id=' . $file['patient_id'] . '" 
                               class="btn btn-info btn-sm mr-2">
                                <i class="fas fa-user mr-1"></i>View Patient
                            </a>';
    }
    
    if (!empty($file['visit_id']) && true) { // For testing - replace with permission check
        $html .= '
                            <a href="/clinic/patient/visit_details.php?visit_id=' . $file['visit_id'] . '" 
                               class="btn btn-info btn-sm mr-2">
                                <i class="fas fa-calendar-check mr-1"></i>View Visit
                            </a>';
    }
    
    if (true) { // For testing - replace with permission check
        $html .= '
                            <button type="button" 
                                    class="btn btn-danger btn-sm" 
                                    onclick="confirmArchive(' . $file['file_id'] . ', \'' . htmlspecialchars(addslashes($file['file_original_name'])) . '\')">
                                <i class="fas fa-archive mr-1"></i>Archive File
                            </button>';
    }
    
    $html .= '
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>';
    
    return $html;
}

// Helper functions
function getFileIcon($fileType) {
    $icons = [
        'pdf' => 'file-pdf',
        'jpg' => 'file-image',
        'jpeg' => 'file-image',
        'png' => 'file-image',
        'gif' => 'file-image',
        'doc' => 'file-word',
        'docx' => 'file-word',
        'xls' => 'file-excel',
        'xlsx' => 'file-excel',
        'txt' => 'file-alt'
    ];
    return $icons[strtolower($fileType)] ?? 'file';
}

function formatBytes($bytes, $precision = 2) {
    $units = ['B', 'KB', 'MB', 'GB', 'TB'];
    $bytes = max($bytes, 0);
    $pow = floor(($bytes ? log($bytes) : 0) / log(1024));
    $pow = min($pow, count($units) - 1);
    $bytes /= pow(1024, $pow);
    return round($bytes, $precision) . ' ' . $units[$pow];
}

function getVisibilityBadge($visibility) {
    $badges = [
        'Private' => 'badge-secondary',
        'Shared' => 'badge-success',
        'Restricted' => 'badge-warning'
    ];
    $class = $badges[$visibility] ?? 'badge-secondary';
    return '<span class="badge ' . $class . '">' . $visibility . '</span>';
}

function getVisitStatusBadge($status) {
    $badges = [
        'Scheduled' => 'badge-info',
        'In Progress' => 'badge-warning',
        'Completed' => 'badge-success',
        'Cancelled' => 'badge-danger'
    ];
    $class = $badges[$status] ?? 'badge-light';
    return '<span class="badge ' . $class . '">' . $status . '</span>';
}

/**
 * Get relative time string (simplified version)
 */
function time_elapsed_string($datetime) {
    $time = strtotime($datetime);
    $now = time();
    $diff = $now - $time;
    
    if ($diff < 60) {
        return 'just now';
    } elseif ($diff < 3600) {
        return floor($diff / 60) . ' minutes ago';
    } elseif ($diff < 86400) {
        return floor($diff / 3600) . ' hours ago';
    } elseif ($diff < 604800) {
        return floor($diff / 86400) . ' days ago';
    } elseif ($diff < 2592000) {
        return floor($diff / 604800) . ' weeks ago';
    } elseif ($diff < 31536000) {
        return floor($diff / 2592000) . ' months ago';
    } else {
        return floor($diff / 31536000) . ' years ago';
    }
}
?>