<?php
// Start output buffering at the VERY beginning
if (ob_get_level()) ob_end_clean();
ob_start();

error_reporting(E_ALL);
ini_set('display_errors', 1);

// Get prescription ID first
$prescription_id = isset($_GET['prescription_id']) ? intval($_GET['prescription_id']) : 0;

if ($prescription_id == 0) {
    // Clean buffer and show error
    ob_clean();
    die('Invalid prescription ID');
}

// Now include files after basic validation
require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/inc_all.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/plugins/TCPDF/tcpdf.php';

// Clean any output that might have been generated by included files
ob_clean();

try {
    // Get company details
    $company_stmt = $mysqli->prepare("
        SELECT company_name, company_address, company_city, company_state, 
               company_zip, company_country, company_phone_country_code, 
               company_phone, company_email, company_website, company_logo,
               company_tax_id
        FROM companies 
        LIMIT 1
    ");
    
    if (!$company_stmt) {
        throw new Exception("Company database error: " . $mysqli->error);
    }
    
    if (!$company_stmt->execute()) {
        throw new Exception("Company execute failed: " . $company_stmt->error);
    }
    
    $company_result = $company_stmt->get_result();
    $company = $company_result->fetch_assoc();

    // Get prescription details
    $stmt = $mysqli->prepare("
        SELECT pr.*, 
               p.patient_id, p.patient_first_name, p.patient_last_name, p.patient_mrn, p.patient_gender, p.patient_dob,
               p.patient_phone, p.patient_email, 
               v.visit_id, v.visit_date, v.visit_type,
               d.department_name,
               doctor_user.user_name as doctor_name
         FROM prescriptions pr 
         JOIN patients p ON pr.prescription_patient_id = p.patient_id 
         LEFT JOIN visits v ON pr.prescription_visit_id = v.visit_id 
         LEFT JOIN departments d ON v.visit_department_id = d.department_id 
         LEFT JOIN users doctor_user ON pr.prescription_doctor_id = doctor_user.user_id
         WHERE pr.prescription_id = ? 
         AND pr.prescription_archived_at IS NULL
    ");
    
    if (!$stmt) {
        throw new Exception("Database error: " . $mysqli->error);
    }
    
    $stmt->bind_param("i", $prescription_id);
    
    if (!$stmt->execute()) {
        throw new Exception("Execute failed: " . $stmt->error);
    }
    
    $result = $stmt->get_result();
    
    if ($result->num_rows == 0) {
        throw new Exception("Prescription not found");
    }

    $prescription = $result->fetch_assoc();

    // Get prescription items
    $items_stmt = $mysqli->prepare("
        SELECT pi.*, d.drug_name, d.drug_generic_name, d.drug_form, d.drug_strength,
                d.drug_manufacturer, d.drug_category
         FROM prescription_items pi
         JOIN drugs d ON pi.pi_drug_id = d.drug_id
         WHERE pi.pi_prescription_id = ?
         ORDER BY pi.pi_id
    ");
    
    if (!$items_stmt) {
        throw new Exception("Database error: " . $mysqli->error);
    }
    
    $items_stmt->bind_param("i", $prescription_id);
    
    if (!$items_stmt->execute()) {
        throw new Exception("Execute failed: " . $items_stmt->error);
    }
    
    $items_result = $items_stmt->get_result();

    $prescription_items = [];
    while ($item = $items_result->fetch_assoc()) {
        $prescription_items[] = $item;
    }

    // Calculate patient age
    $patient_age = '';
    if (!empty($prescription['patient_dob'])) {
        $birthDate = new DateTime($prescription['patient_dob']);
        $today = new DateTime();
        $age = $today->diff($birthDate)->y;
        $patient_age = "$age years";
    }

    // Build company address string
    $company_address = '';
    if (!empty($company['company_address'])) {
        $company_address = $company['company_address'];
        if (!empty($company['company_city'])) {
            $company_address .= ', ' . $company['company_city'];
        }
        if (!empty($company['company_state'])) {
            $company_address .= ', ' . $company['company_state'];
        }
        if (!empty($company['company_zip'])) {
            $company_address .= ' ' . $company['company_zip'];
        }
        if (!empty($company['company_country'])) {
            $company_address .= ', ' . $company['company_country'];
        }
    }

    // Build company phone string
    $company_phone = '';
    if (!empty($company['company_phone'])) {
        $company_phone = $company['company_phone'];
        if (!empty($company['company_phone_country_code'])) {
            $company_phone = '+' . $company['company_phone_country_code'] . ' ' . $company_phone;
        }
    }

    // Create new PDF document
    $pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);

    // Set document information
    $pdf->SetCreator($company['company_name'] ?? 'Hospital Management System');
    $pdf->SetAuthor($prescription['doctor_name']);
    $pdf->SetTitle('Prescription #' . $prescription_id);
    $pdf->SetSubject('Medical Prescription');

    // Remove default header/footer
    $pdf->setPrintHeader(false);
    $pdf->setPrintFooter(false);

    // Set margins
    $pdf->SetMargins(15, 15, 15);
    $pdf->SetAutoPageBreak(TRUE, 15);

    // Add a page
    $pdf->AddPage();

    // Add RX watermark
    $pdf->SetAlpha(0.1);
    $pdf->SetFont('helvetica', 'B', 120);
    $pdf->SetTextColor(200, 200, 200);
    
    // Save current position and rotate
    $pdf->StartTransform();
    $pdf->Rotate(45, 105, 150);
    $pdf->Text(40, 100, 'R X');
    $pdf->StopTransform();
    
    // RESET everything properly after rotation
    $pdf->SetAlpha(1);
    $pdf->SetTextColor(0, 0, 0);
    $pdf->SetFont('helvetica', '', 10);
    
    // Reset to top of page for content
    $pdf->SetY(15);

    // Header with company info - USING ACTUAL COMPANY DATA
    $pdf->SetFont('helvetica', 'B', 16);
    $pdf->Cell(0, 8, 'MEDICAL PRESCRIPTION', 0, 1, 'C');
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->Cell(0, 6, $company['company_name'] ?? 'Hospital Management System', 0, 1, 'C');
    $pdf->SetFont('helvetica', '', 10);
    
    // Company address
    if (!empty($company_address)) {
        $pdf->Cell(0, 5, $company_address, 0, 1, 'C');
    }
    
    // Company contact info
    $contact_info = '';
    if (!empty($company_phone)) {
        $contact_info .= 'Phone: ' . $company_phone;
    }
    if (!empty($company['company_email'])) {
        if (!empty($contact_info)) $contact_info .= ' | ';
        $contact_info .= 'Email: ' . $company['company_email'];
    }
    if (!empty($company['company_website'])) {
        if (!empty($contact_info)) $contact_info .= ' | ';
        $contact_info .= 'Web: ' . $company['company_website'];
    }
    
    if (!empty($contact_info)) {
        $pdf->Cell(0, 5, $contact_info, 0, 1, 'C');
    }
    
    // Tax ID if available
    if (!empty($company['company_tax_id'])) {
        $pdf->Cell(0, 5, 'Tax ID: ' . $company['company_tax_id'], 0, 1, 'C');
    }
    
    $pdf->Ln(8);

    // Prescription header
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->Cell(0, 6, 'PRESCRIPTION #' . $prescription_id, 0, 1, 'L');
    $pdf->SetFont('helvetica', '', 10);
    $pdf->Cell(0, 5, 'Date: ' . date('F j, Y', strtotime($prescription['prescription_date'])), 0, 1, 'L');
    $pdf->Cell(0, 5, 'Time: ' . date('g:i A', strtotime($prescription['prescription_date'])), 0, 1, 'L');
    
    $pdf->Ln(5);

    // Patient and Doctor information in two columns
    $pdf->SetFont('helvetica', 'B', 11);
    $pdf->Cell(95, 7, 'PATIENT INFORMATION', 1, 0, 'C');
    $pdf->Cell(95, 7, 'PRESCRIBER INFORMATION', 1, 1, 'C');
    
    $pdf->SetFont('helvetica', '', 9);
    
    // Patient column
    $pdf->Cell(95, 6, 'Name: ' . $prescription['patient_name'], 1, 0, 'L');
    $pdf->Cell(95, 6, 'Name: Dr. ' . $prescription['doctor_name'], 1, 1, 'L');
    
    $pdf->Cell(95, 6, 'MRN: ' . $prescription['patient_mrn'], 1, 0, 'L');
    $pdf->Cell(95, 6, 'Department: ' . ($prescription['department_name'] ?? 'General Medicine'), 1, 1, 'L');
    
    $pdf->Cell(95, 6, 'Age: ' . $patient_age, 1, 0, 'L');
    $pdf->Cell(95, 6, 'Date: ' . date('m/d/Y', strtotime($prescription['prescription_date'])), 1, 1, 'L');
    
    $pdf->Cell(95, 6, 'Gender: ' . $prescription['patient_gender'], 1, 0, 'L');
    $pdf->Cell(95, 6, '', 1, 1, 'L');
    
    if (!empty($prescription['patient_dob'])) {
        $pdf->Cell(95, 6, 'DOB: ' . date('m/d/Y', strtotime($prescription['patient_dob'])), 1, 0, 'L');
        $pdf->Cell(95, 6, '', 1, 1, 'L');
    }

    $pdf->Ln(8);

    // Medications header
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->SetFillColor(240, 240, 240);
    $pdf->Cell(0, 7, 'PRESCRIBED MEDICATIONS', 0, 1, 'L', true);
    $pdf->Ln(3);

    // Medications table header
    $pdf->SetFont('helvetica', 'B', 9);
    $pdf->SetFillColor(220, 220, 220);
    $pdf->Cell(70, 7, 'Medication', 1, 0, 'C', true);
    $pdf->Cell(20, 7, 'Dosage', 1, 0, 'C', true);
    $pdf->Cell(25, 7, 'Frequency', 1, 0, 'C', true);
    $pdf->Cell(25, 7, 'Duration', 1, 0, 'C', true);
    $pdf->Cell(20, 7, 'Quantity', 1, 0, 'C', true);
    $pdf->Cell(30, 7, 'Instructions', 1, 1, 'C', true);

    // Medications content
    $pdf->SetFont('helvetica', '', 8);
    foreach ($prescription_items as $item) {
        // Medication name with generic name if available
        $medication = $item['drug_name'];
        if (!empty($item['drug_generic_name'])) {
            $medication .= " (" . $item['drug_generic_name'] . ")";
        }
        if (!empty($item['drug_strength'])) {
            $medication .= "\n" . $item['drug_strength'];
        }
        
        $pdf->MultiCell(70, 12, $medication, 1, 'L', false, 0);
        $pdf->MultiCell(20, 12, $item['pi_dosage'] ?? 'N/A', 1, 'C', false, 0);
        $pdf->MultiCell(25, 12, $item['pi_frequency'] ?? 'N/A', 1, 'C', false, 0);
        $pdf->MultiCell(25, 12, $item['pi_duration'] ?? 'N/A', 1, 'C', false, 0);
        $pdf->MultiCell(20, 12, $item['pi_quantity'], 1, 'C', false, 0);
        $pdf->MultiCell(30, 12, $item['pi_instructions'] ?? 'As directed', 1, 'L', false, 1);
    }

    $pdf->Ln(8);

    // Additional notes
    if (!empty($prescription['prescription_notes'])) {
        $pdf->SetFont('helvetica', 'B', 10);
        $pdf->Cell(0, 6, 'ADDITIONAL NOTES:', 0, 1, 'L');
        $pdf->SetFont('helvetica', '', 9);
        $pdf->MultiCell(0, 5, $prescription['prescription_notes'], 0, 'L');
        $pdf->Ln(5);
    }

    // Important instructions
    $pdf->SetFont('helvetica', 'B', 9);
    $pdf->SetTextColor(255, 0, 0);
    $pdf->Cell(0, 6, 'IMPORTANT: Take medications exactly as prescribed. Do not share medications.', 0, 1, 'C');
    $pdf->SetTextColor(0, 0, 0);

    $pdf->Ln(10);

    // Signature area
    $pdf->SetFont('helvetica', 'B', 10);
    $pdf->Cell(0, 5, 'Prescriber Signature:', 0, 1, 'L');
    $pdf->Ln(8);
    
    // Signature line
    $pdf->Line(20, $pdf->GetY(), 80, $pdf->GetY());
    $pdf->SetFont('helvetica', '', 9);
    $pdf->Cell(60, 5, 'Dr. ' . $prescription['doctor_name'], 0, 0, 'L');
    $pdf->Cell(0, 5, date('m/d/Y'), 0, 1, 'R');
    
    $pdf->Ln(8);
    
    // Footer with company info
    $pdf->SetFont('helvetica', 'I', 8);
    $pdf->SetTextColor(128, 128, 128);
    $pdf->Cell(0, 4, 'This is a computer-generated prescription from ' . ($company['company_name'] ?? 'Hospital Management System') . '.', 0, 1, 'C');
    $pdf->Cell(0, 4, 'No physical signature is required. For questions, please contact the prescribing physician.', 0, 1, 'C');
    $pdf->Cell(0, 4, 'Document generated on: ' . date('F j, Y \a\t g:i A'), 0, 1, 'C');

    // Clean output buffer completely before sending PDF
    ob_clean();
    
    // Output PDF
    $pdf->Output('prescription_' . $prescription_id . '.pdf', 'I');
    exit;
    
} catch (Exception $e) {
    // Clean buffer and show error
    ob_clean();
    die('PDF Generation Error: ' . $e->getMessage());
}